server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true



spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/fcsmall?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: jiheon2234
    password: '0000'
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create-drop #??
    show-sql: true


logging:
  level:
    root: info




